name: Ninibear
options:
  bundleIdPrefix: com.ninibear
targets:
  Ninibear:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: .
        excludes:
          - .github/**/*
          - README.md
          - project.yml
          - build.yml
          - Info.plist
    info:
      path: Info.plist
      properties:
        CFBundleDisplayName: "Ninibear动动钟"
        CFBundleShortVersionString: "0.1.0"
        CFBundleVersion: "1"
        UILaunchScreen: {}
        ITSAppUsesNonExemptEncryption: false
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.ninibear.clock
        SWIFT_VERSION: "5.0"
        CODE_SIGNING_ALLOWED: NO
        CODE_SIGNING_REQUIRED: NO
        CODE_SIGN_IDENTITY: ""
